title: Le fil d'Ariane
author: Valéry Farcy
email: hello@nepasecrire.com
description: >-
  Une exploration au carrefour de la philosophie, de l'IA, de la systémique et de la zététique.

# Ne modifiez pas ce qui suit
theme: minima
plugins:
  - jekyll-feed
